version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.1-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: |
            docker build --file ./Dockerfile.test --tag kfirz/deployster:test-${CIRCLE_SHA1:-0.0.0} .
