steps:

  ######################################################################################################################
  # Build the "deployster" image, which is the main executable, and the "dresource" image, which serves as the base
  # image for all our other resource images.
  # Build both images in parallel and wait for both of them to finish.
  ######################################################################################################################
  - label: kfirz/deployster
    plugins: { docker-login#v1.0.0: { username: arikkfir} }
    command:
      - docker build --build-arg "CODECOV_TOKEN=515ac87b-0f3f-45e2-a46e-20aa32baf273" --build-arg "VERSION=${BUILDKITE_TAG:-$BUILDKITE_COMMIT}" -t kfirz/deployster:${BUILDKITE_TAG:-$BUILDKITE_COMMIT} -f ./Dockerfile .
      - docker push kfirz/deployster:${BUILDKITE_TAG:-$BUILDKITE_COMMIT}
  - label: kfirz/dresource
    plugins: { docker-login#v1.0.0: { username: arikkfir} }
    command: ./.buildkite/build-resource-image.sh dresource ${BUILDKITE_TAG:-$BUILDKITE_COMMIT}
  - wait

  ######################################################################################################################
  # Build the "k8s" & "gcp" images, which serve as base images for our GCP & Kubernetes resource images.
  ######################################################################################################################
  - label: kfirz/gcp
    plugins: { docker-login#v1.0.0: { username: arikkfir} }
    command: ./.buildkite/build-resource-image.sh gcp ${BUILDKITE_TAG:-$BUILDKITE_COMMIT}
  - label: kfirz/k8s
    plugins: { docker-login#v1.0.0: { username: arikkfir} }
    command: ./.buildkite/build-resource-image.sh k8s ${BUILDKITE_TAG:-$BUILDKITE_COMMIT}
  - wait

  ######################################################################################################################
  # Upload additional pipeline steps which will build all our other images.
  ######################################################################################################################
  - label: Augment pipeline
    command: ./.buildkite/generate-resource-images-pipeline.sh ${BUILDKITE_TAG:-$BUILDKITE_COMMIT} | buildkite-agent pipeline upload
